// <auto-generated />
namespace Unicasa.API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class UnicasaMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UnicasaMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201808020452323_UnicasaMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
